spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.idle-timeout=${DB_IDLE_TIMEOUT}
spring.datasource.hikari.maximum-pool-size=${DB_MAXIMUM_POOL_SIZE}
spring.datasource.hikari.minimum-idle=${DB_MINIMUM_IDLE}
spring.datasource.hikari.connection-timeout=${DB_CONNECTION_TIMEOUT}
spring.datasource.hikari.max-lifetime=${DB_MAX_LIFETIME}

spring.flyway.enabled=${DB_FLYWAY_ENABLED}
spring.flyway.baseline-on-migrate=${DB_FLYWAY_BASELINE_ON_MIGRATE}

server.undertow.accesslog.enabled=${UNDERTOW_ACCESSLOG_ENABLED}
server.undertow.accesslog.pattern=${UNDERTOW_ACCESSLOG_PATTERN}
server.undertow.threads.io=${UNDERTOW_IO_THREADS}
server.undertow.threads.worker=${UNDERTOW_WORKER_THREADS}
server.undertow.max-http-post-size=${UNDERTOW_MAX_HTTP_POST_SIZE}

logging.level.org.springframework.security=${LOGGING_LEVEL_SPRING_SECURITY}

app.internal.api-key=${WORKFLOW_SERVICE_INTERNAL_API_KEY}