spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=workflow
spring.datasource.username=postgres
spring.datasource.password=12345

spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.repair-on-migrate=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8880/oauth2/jwks

server.undertow.accesslog.enabled=false
server.undertow.accesslog.pattern=%h %l %u %t "%r" %s %b
server.undertow.threads.io=4
server.undertow.threads.worker=32
server.undertow.max-http-post-size=10485760

logging.level.org.springframework.security=INFO

app.webrtc.stun-urls=stun:stun.l.google.com:19302
app.webrtc.turn-urls=
app.webrtc.turn-username=
app.webrtc.turn-credential=

app.room.media.social.audio-enabled=true
app.room.media.social.video-enabled=true
app.room.media.social.chat-enabled=true
app.room.media.social.mic-enabled=false
app.room.media.social.video-resolution=480p
app.room.media.social.default-members=10

app.room.media.team.audio-enabled=true
app.room.media.team.video-enabled=true
app.room.media.team.chat-enabled=true
app.room.media.team.mic-enabled=true
app.room.media.team.video-resolution=720p
app.room.media.team.default-max-members=6
app.room.media.team.default-minimum-members=4




