services:
  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "49152-49200:49152-49200/udp"
    volumes:
      - ./coturn/turnserver.conf:/etc/turnserver.conf:ro
      - ./coturn/turnusers.txt:/var/lib/turn/turnusers.txt:ro
    command: ["-c", "/etc/turnserver.conf"]
