export { default as Welcome } from './pages/Welcome'
export { default as SignUp } from './pages/SignUp'
export { default as ConfirmMail } from './pages/ConfirmMail'
export { default as ResetPassword } from './pages/ResetPassword'
export { default as VerifyEmail } from './pages/VerifyEmail'
