spring.application.name=together.gateway
spring.profiles.active=local

server.port=8890
server.shutdown=graceful
server.forward-headers-strategy=framework

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
